### ISSUE TITLE
Sibling selector support?

### ISSUE THREAD

**Issue by mesteiral** [pygy/j2c#6]
Is it possible to express this CSS snippet as a j2c sheet? If possible, it doesn't seem obvious.

```css
.switch { /* ... */ }
.switch__input { /* */  }
.switch__input:checked + .switch__toggle { /* */ }
.switch__input:checked + .switch__toggle:before { /* */ }
.switch__input:not(:checked) + .switch__toggle:before { /* */ }
```

Example DOM:

```html
<label class="switch">
  <input class="switch__input" type="checkbox">
  <div class="switch__toggle"></div>
</label>
```

My intent would be making the `switch__toggle` styling dependent only on view-related concerns (i.e. whether the sibling input is `:checked`), thus avoiding introducing new classes to reflect component state.

**Comment by pygy** [comment]
This should do it:

```JavaScript
j2c.sheet({
    ".switch": { /* ... */ },
    ".switch__input": { 
        /* properties fot `.switch__input`, */
        ":checked + .switch__toggle" : {
            /* properties for `.switch__input:checked  + .switch__toggle`, */
            ":before": {
                /* properties for `.switch__input:checked  + .switch__toggle:before` */
            }
        },
        ":not(:checked) + .switch__toggle:before" : { 
            /* properties for `.switch__input:not(:checked)  + .switch__toggle:before` */
        }
    }
})
```

Alternatively, you can forego nesting and use 

```JavaScript
j2c.sheet({
    ".switch": { /* ... */ },
    ".switch__input": { /* */  },
    ".switch__input:checked + .switch__toggle": { /* */ },
    ".switch__input:checked + .switch__toggle:before": { /* */ },
    ".switch__input:not(:checked) + .switch__toggle:before": { /* */ }
})
```

**Comment by mesteiral** [comment]
Thanks! Indeed it works with `j2c.sheet`. 

On the other hand, I passed this to `j2c.scoped` and was hoping it would recognize `.switch__toggle` (or anything that comes after `+`) as a class name and also uniquify it. While selectors might not be the intent of object keys for `j2c.scoped`, I was looking after a way to seamlessly convert an inherited stylesheet with many occurrences of sibling selectors to a set of scoped rules for use with a Mithril component.

Is this feature out of scope for this tool?

**Comment by pygy** [comment]
In the `next` branch, j2c.scoped is out, and j2c.sheet works more or less as you described, localizing all names unless wrapped in `:global()` pseudo-selectors or in `"@global":{ ... }` blocks.

I've been meaning to publish it for several months now (I must update the docs before that), but real life got in the way (medical issues in the family that disrupt my day to day life) and I have a hard time to find the energy to do it when I have some free time...

You can give it a try if you want.

**Comment by pygy** [comment]
Pre-release versions of `v0.8` are now out on npm as `v0.8.0-pre.N` with N = 2 as of writing. You can give it a spin if you want.
